steps:
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '--no-cache','true', '-t', 'gcr.io/$PROJECT_ID/ratingservice:$BRANCH_NAME-$REVISION_ID',
                  '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ratingservice:$BRANCH_NAME-$REVISION_ID']
